version: '3.2'
services:
  p4d.helix:
    build:
      context: helix-p4d
      dockerfile: Dockerfile
    hostname: p4d
    domainname: helix
    env_file:
      - helix.env
    ports:
      - 4000:1666
    tty: true

  build.helix:
    build:
      context: helix-build
      dockerfile: Dockerfile
    hostname: build
    domainname: helix
    env_file:
      - helix.env
    ports:
      - 4001:1666
    depends_on:
      - p4d.helix
    tty: true

  swarm.helix:
    build:
      context: helix-swarm
      dockerfile: Dockerfile
    hostname: swarm
    domainname: helix
    env_file:
      - helix.env
    ports:
      - 5080:80
    depends_on:
      - p4d.helix
    tty: true

  jira.helix:
    build:
      context: jira
      dockerfile: Dockerfile
    hostname: jira
    domainname: helix
    env_file:
      - helix.env
    ports:
      - 7070:8080
    volumes:
      - ./volumes/jira-data:/var/atlassian/jira
      - ./volumes/jira-logs:/opt/atlassian/jira/logs
    tty: true