version: '2'
services:
  p4d.helix:
    build:
      context: helix-p4d
      dockerfile: Dockerfile.xenial
    hostname: p4d
    domainname: helix
    env_file:
      - helix.env
    ports:
      - 4000:1666
    tty: true

  build.helix:
    build:
      context: helix-build
      dockerfile: Dockerfile.xenial
    hostname: build
    domainname: helix
    env_file:
      - helix.env
    ports:
      - 4001:1666
    depends_on:
      - p4d.helix
    tty: true

  swarm.helix:
    build:
      context: helix-swarm
      dockerfile: Dockerfile.xenial
    hostname: swarm
    domainname: helix
    env_file:
      - helix.env
    ports:
      - 5080:80
    depends_on:
      - p4d.helix
    tty: true